### ISSUE TITLE
[Feature Req]: Blanket `stepci run` support

### ISSUE THREAD

**Issue by polyphilz** [stepci/stepci#178]
If I have a lot of `<test-name>.stepci.yml` files littered in many different directories, is there an existing way to just run `stepci run` or similar at the root of my proj directory and have that run all relevant `.*.stepci.yml` files (concurrently ideally)?

If not, would make for a great feature :)

**Comment by mishushakov** [comment]
The current workflow is that you have all your tests in a single workflow.yml file. We then run them in parallel. If you want to split tests across multiple files, we have "include" option for that:
https://docs.stepci.com/guides/organising-workflows.html

Let me know if this option works for you, otherwise we might think about a different option

**Comment by mishushakov** [comment]
Btw. if you have any other feedback or anything, you can just schedule a call here: https://cal.com/wissmueller/step-ci-enterprise-support

**Comment by polyphilz** [comment]
Got it, this should work for us for now since we don't have an absolute crazy number of tests where `workflow.yml` might get too unruly - thanks!

**Comment by mishushakov** [comment]
We have now replaced include with a better option, using $refs, similar to your OpenAPI spec:
https://docs.stepci.com/guides/organising-workflows.html

This way you could also re-use steps and other props
